<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'product_name' => 'iPhone 13 Pro Max',
                'description' => 'Smartphone cao cấp với màn hình OLED 6.7 inch, chip A15 Bionic và camera chuyên nghiệp.',
                'price' => 1099.99,
                'quantity' => 50,
                'category_id' => 1,
                'color_id' => 1,
                'image1' => 'ip1.jpg',
                'image2' => 'ip2.jpg',
                'image3' => 'ip3.jpg',
                'rating' => 5,
            ],
            [
                'product_name' => 'Samsung Galaxy S21 Ultra',
                'description' => 'Điện thoại thông minh với màn hình 6.8 inch, camera 108MP, pin dung lượng lớn và hiệu năng mạnh mẽ.',
                'price' => 1199.99,
                'quantity' => 30,
                'category_id' => 2,
                'color_id' => 2,
                'image1' => 'ss2.jpg',
                'image2' => 'ip4.jpg',
                'image3' => 'vv1.jpg',
                'rating' => 5,
            ],
            [
                'product_name' => 'Xiaomi Mi 11',
                'description' => 'Thiết bị tầm trung với màn hình AMOLED 6.81 inch, chip Snapdragon 888 và pin 4600mAh.',
                'price' => 749.99,
                'quantity' => 40,
                'category_id' => 1,
                'color_id' => 1,
                'image1' => 'vv2.jpg',
                'image2' => 'ip3.jpg',
                'image3' => 'ip2.jpg',
                'rating' => 4,
            ],
            [
                'product_name' => 'OPPO Find X3 Pro',
                'description' => 'Điện thoại với màn hình 6.7 inch, camera chất lượng cao và khả năng sạc nhanh 65W.',
                'price' => 899.99,
                'quantity' => 25,
                'category_id' => 2,
                'color_id' => 2,
                'image1' => 'ip1.jpg',
                'image2' => 'ip4.jpg',
                'image3' => 'vv1.jpg',
                'rating' => 4,
            ],
            [
                'product_name' => 'Sony Xperia 1 III',
                'description' => 'Smartphone màn hình 4K 6.5 inch, camera chụp ảnh chuyên nghiệp và âm thanh Dolby Atmos.',
                'price' => 1299.99,
                'quantity' => 20,
                'category_id' => 1,
                'color_id' => 1,
                'image1' => 'vv2.jpg',
                'image2' => 'ss2.jpg',
                'image3' => 'ip2.jpg',
                'rating' => 5,
            ],
            [
                'product_name' => 'Nokia 8.3 5G',
                'description' => 'Điện thoại 5G với màn hình 6.81 inch, camera 64MP và pin 4500mAh.',
                'price' => 699.99,
                'quantity' => 30,
                'category_id' => 2,
                'color_id' => 2,
                'image1' => 'ip1.jpg',
                'image2' => 'vv1.jpg',
                'image3' => 'ip3.jpg',
                'rating' => 4,
            ],
            [
                'product_name' => 'Realme GT 5G',
                'description' => 'Smartphone hiệu năng cao với màn hình 6.43 inch, chip Snapdragon 888 và sạc nhanh 65W.',
                'price' => 599.99,
                'quantity' => 35,
                'category_id' => 1,
                'color_id' => 1,
                'image1' => 'ip4.jpg',
                'image2' => 'vv2.jpg',
                'image3' => 'ss2.jpg',
                'rating' => 5,
            ],
            [
                'product_name' => 'Vivo X60 Pro',
                'description' => 'Điện thoại với camera Zeiss chất lượng cao và hiệu năng mượt mà.',
                'price' => 849.99,
                'quantity' => 20,
                'category_id' => 2,
                'color_id' => 2,
                'image1' => 'ip3.jpg',
                'image2' => 'ip1.jpg',
                'image3' => 'vv1.jpg',
                'rating' => 4,
            ],
            [
                'product_name' => 'OnePlus 9',
                'description' => 'Điện thoại với màn hình AMOLED 6.55 inch, camera Hasselblad và sạc nhanh 65W.',
                'price' => 729.99,
                'quantity' => 30,
                'category_id' => 1,
                'color_id' => 1,
                'image1' => 'ss2.jpg',
                'image2' => 'ip4.jpg',
                'image3' => 'vv2.jpg',
                'rating' => 5,
            ],
            [
                'product_name' => 'Motorola Edge 20 Pro',
                'description' => 'Điện thoại với màn hình 6.7 inch, camera 108MP và khả năng 5G.',
                'price' => 799.99,
                'quantity' => 25,
                'category_id' => 2,
                'color_id' => 2,
                'image1' => 'ip2.jpg',
                'image2' => 'ip1.jpg',
                'image3' => 'vv1.jpg',
                'rating' => 4,
            ],
            [
                'product_name' => 'Huawei P40 Pro',
                'description' => 'Smartphone với camera Leica và hiệu năng mạnh mẽ.',
                'price' => 999.99,
                'quantity' => 15,
                'category_id' => 1,
                'color_id' => 1,
                'image1' => 'ip3.jpg',
                'image2' => 'ss2.jpg',
                'image3' => 'vv2.jpg',
                'rating' => 5,
            ],
            [
                'product_name' => 'Google Pixel 5',
                'description' => 'Điện thoại thông minh với camera chất lượng cao và Android thuần.',
                'price' => 699.99,
                'quantity' => 30,
                'category_id' => 2,
                'color_id' => 2,
                'image1' => 'ip1.jpg',
                'image2' => 'vv1.jpg',
                'image3' => 'ip2.jpg',
                'rating' => 4,
            ],
            [
                'product_name' => 'Asus ROG Phone 5',
                'description' => 'Điện thoại chơi game với hiệu năng cao và màn hình 144Hz.',
                'price' => 999.99,
                'quantity' => 20,
                'category_id' => 1,
                'color_id' => 1,
                'image1' => 'ip4.jpg',
                'image2' => 'ss2.jpg',
                'image3' => 'vv1.jpg',
                'rating' => 5,
            ],
            [
                'product_name' => 'Honor 50',
                'description' => 'Điện thoại tầm trung với màn hình OLED và camera đa năng.',
                'price' => 499.99,
                'quantity' => 25,
                'category_id' => 2,
                'color_id' => 2,
                'image1' => 'vv2.jpg',
                'image2' => 'ip1.jpg',
                'image3' => 'ip2.jpg',
                'rating' => 4,
            ],
            [
                'product_name' => 'Nokia 5.4',
                'description' => 'Điện thoại với hiệu năng ổn định và camera chất lượng tốt.',
                'price' => 249.99,
                'quantity' => 40,
                'category_id' => 1,
                'color_id' => 1,
                'image1' => 'ip3.jpg',
                'image2' => 'ip4.jpg',
                'image3' => 'vv1.jpg',
                'rating' => 4,
            ],
            [
                'product_name' => 'TCL 20 Pro 5G',
                'description' => 'Điện thoại với màn hình AMOLED và camera 48MP.',
                'price' => 399.99,
                'quantity' => 30,
                'category_id' => 2,
                'color_id' => 2,
                'image1' => 'ip1.jpg',
                'image2' => 'ss2.jpg',
                'image3' => 'ip2.jpg',
                'rating' => 4,
            ],
            [
                'product_name' => 'Infinix Zero 8',
                'description' => 'Điện thoại với màn hình 90Hz và camera kép.',
                'price' => 299.99,
                'quantity' => 20,
                'category_id' => 1,
                'color_id' => 1,
                'image1' => 'vv2.jpg',
                'image2' => 'ip3.jpg',
                'image3' => 'ip4.jpg',
                'rating' => 4,
            ],
            [
                'product_name' => 'ZTE Axon 20 5G',
                'description' => 'Điện thoại với camera ẩn dưới màn hình và khả năng 5G.',
                'price' => 499.99,
                'quantity' => 15,
                'category_id' => 2,
                'color_id' => 2,
                'image1' => 'ip1.jpg',
                'image2' => 'ip2.jpg',
                'image3' => 'vv1.jpg',
                'rating' => 4,
            ],
        ]);
    }
}
