<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'product_name' => 'T-Shirt Classic',
                'description' => 'A comfortable cotton T-shirt',
                'price' => 19.99,
                'quantity' => 50,
                'category_id' => 1,
                'color_id' => 1,
                'image1' => 'ip1.jpg',
                'image2' => 'tshirt_classic_2.jpg',
                'image3' => null,
                'rating' => 4,
            ],
            [
                'product_name' => 'Jeans Regular Fit',
                'description' => 'Classic denim jeans with regular fit.',
                'price' => 39.99,
                'quantity' => 30,
                'category_id' => 2,
                'color_id' => 2,
                'image1' => 'ip2.jpg',
                'image2' => null,
                'image3' => null,
                'rating' => 5,
            ],
            [
                'product_name' => 'Hoodie Sport',
                'description' => 'A stylish hoodie for everyday wear.',
                'price' => 49.99,
                'quantity' => 40,
                'category_id' => 1,
                'color_id' => 1,
                'image1' => 'ip3.jpg',
                'image2' => 'hoodie_sport_2.jpg',
                'image3' => null,
                'rating' => 3,
            ],
            [
                'product_name' => 'Sneakers Low Top',
                'description' => 'Comfortable low-top sneakers.',
                'price' => 59.99,
                'quantity' => 25,
                'category_id' => 2,
                'color_id' => 2,
                'image1' => 'ip2.jpg',
                'image2' => null,
                'image3' => null,
                'rating' => 4,
            ],
            [
                'product_name' => 'Leather Belt',
                'description' => 'Premium leather belt.',
                'price' => 24.99,
                'quantity' => 100,
                'category_id' => 1,
                'color_id' => 1,
                'image1' => 'belt_leather_1.jpg',
                'image2' => null,
                'image3' => null,
                'rating' => 5,
            ],
            [
                'product_name' => 'Baseball Cap',
                'description' => 'Adjustable baseball cap with embroidered logo.',
                'price' => 15.99,
                'quantity' => 75,
                'category_id' => 2,
                'color_id' => 2,
                'image1' => 'cap_baseball_1.jpg',
                'image2' => null,
                'image3' => null,
                'rating' => 4,
            ],
            [
                'product_name' => 'Wool Scarf',
                'description' => 'Warm and cozy wool scarf.',
                'price' => 19.99,
                'quantity' => 60,
                'category_id' => 1,
                'color_id' => 2,
                'image1' => 'scarf_wool_1.jpg',
                'image2' => null,
                'image3' => null,
                'rating' => 4,
            ],
            [
                'product_name' => 'Running Shoes',
                'description' => 'Lightweight running shoes for maximum comfort.',
                'price' => 69.99,
                'quantity' => 35,
                'category_id' => 2,
                'color_id' => 1,
                'image1' => 'shoes_running_1.jpg',
                'image2' => null,
                'image3' => null,
                'rating' => 5,
            ],
            [
                'product_name' => 'Formal Shirt',
                'description' => 'Elegant formal shirt for special occasions.',
                'price' => 45.99,
                'quantity' => 20,
                'category_id' => 1,
                'color_id' => 1,
                'image1' => 'shirt_formal_1.jpg',
                'image2' => 'shirt_formal_2.jpg',
                'image3' => null,
                'rating' => 4,
            ],
            [
                'product_name' => 'Casual Shorts',
                'description' => 'Lightweight and comfortable casual shorts.',
                'price' => 29.99,
                'quantity' => 45,
                'category_id' => 2,
                'color_id' => 2,
                'image1' => 'shorts_casual_1.jpg',
                'image2' => null,
                'image3' => null,
                'rating' => 3,
            ],
            [
                'product_name' => 'Cotton Socks',
                'description' => 'Pack of 3 cotton socks.',
                'price' => 9.99,
                'quantity' => 150,
                'category_id' => 1,
                'color_id' => 1,
                'image1' => 'socks_cotton_1.jpg',
                'image2' => null,
                'image3' => null,
                'rating' => 5,
            ],
            [
                'product_name' => 'Denim Jacket',
                'description' => 'Classic denim jacket with a vintage look.',
                'price' => 69.99,
                'quantity' => 18,
                'category_id' => 2,
                'color_id' => 2,
                'image1' => 'jacket_denim_1.jpg',
                'image2' => 'jacket_denim_2.jpg',
                'image3' => null,
                'rating' => 4,
            ],
            [
                'product_name' => 'Wool Hat',
                'description' => 'Warm wool hat for cold days.',
                'price' => 12.99,
                'quantity' => 65,
                'category_id' => 1,
                'color_id' => 1,
                'image1' => 'hat_wool_1.jpg',
                'image2' => null,
                'image3' => null,
                'rating' => 5,
            ],
            [
                'product_name' => 'Gym Bag',
                'description' => 'Spacious gym bag with multiple compartments.',
                'price' => 39.99,
                'quantity' => 40,
                'category_id' => 2,
                'color_id' => 2,
                'image1' => 'gym_bag_1.jpg',
                'image2' => null,
                'image3' => null,
                'rating' => 4,
            ],
            [
                'product_name' => 'Leather Gloves',
                'description' => 'Premium leather gloves for winter.',
                'price' => 29.99,
                'quantity' => 35,
                'category_id' => 1,
                'color_id' => 1,
                'image1' => 'gloves_leather_1.jpg',
                'image2' => null,
                'image3' => null,
                'rating' => 5,
            ],
            [
                'product_name' => 'Flip Flops',
                'description' => 'Casual flip flops for the beach.',
                'price' => 14.99,
                'quantity' => 70,
                'category_id' => 2,
                'color_id' => 2,
                'image1' => 'flip_flops_1.jpg',
                'image2' => null,
                'image3' => null,
                'rating' => 3,
            ],
            [
                'product_name' => 'Backpack',
                'description' => 'Durable backpack for everyday use.',
                'price' => 49.99,
                'quantity' => 25,
                'category_id' => 1,
                'color_id' => 2,
                'image1' => 'backpack_1.jpg',
                'image2' => null,
                'image3' => null,
                'rating' => 4,
            ],
            [
                'product_name' => 'Leather Wallet',
                'description' => 'Sleek leather wallet with multiple card slots.',
                'price' => 24.99,
                'quantity' => 80,
                'category_id' => 2,
                'color_id' => 1,
                'image1' => 'wallet_leather_1.jpg',
                'image2' => null,
                'image3' => null,
                'rating' => 5,
            ],
            [
                'product_name' => 'Sunglasses',
                'description' => 'Stylish sunglasses with UV protection.',
                'price' => 29.99,
                'quantity' => 55,
                'category_id' => 1,
                'color_id' => 2,
                'image1' => 'sunglasses_1.jpg',
                'image2' => null,
                'image3' => null,
                'rating' => 5
            ],
            [
                'product_name' => 'LAze Short',
                'description' => 'Stylish sunglasses with UV protection.',
                'price' => 29.99,
                'quantity' => 55,
                'category_id' => 1,
                'color_id' => 2,
                'image1' => 'sunglasses_1.jpg',
                'image2' => null,
                'image3' => null,
                'rating' => 5
            ],
        ]);
    }
}
